spring.application.name=spring
spring.datasource.url=jdbc:postgresql://localhost:5432/Training
spring.datasource.username=Tanmay
spring.datasource.password=0256
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
